version: 2.1
#orbs:
#  codecov: codecov/codecov@1.0.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: pip install --no-cache-dir pipenv && pipenv install --dev
      - run: pipenv run -- make test
      #- codecov/upload:
      #    file: htmlcov/